apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
data:
  GITLAB_OMNIBUS_CONFIG: | 
      external_url 'http://{{ .Values.gitlab.global.hosts.domain }}';
      manage_storage_directories['manage_etc'] = false;
      postgresql['enable'] = false;
      redis['enable'] = false;
      gitlab_rails['db_adapter'] = 'postgresql';
      gitlab_rails['db_database'] = '{{ .Values.persistence.dbName }}';
      gitlab_rails['db_encoding'] = 'utf8';
      gitlab_rails['db_host'] = {{ .Values.persistence.dbHost | quote }};
      gitlab_rails['db_username'] = {{ .Values.persistence.dbUser | quote }};
      gitlab_rails['db_password'] = {{ .Values.persistence.dbPassword | quote }};
      gitlab_rails['db_port'] = "5432";
      gitlab_rails['gitlab_shell_ssh_port'] = 30022;
      gitlab_rails['redis_host'] = 'redis';
      gitlab_rails['redis_port'] = '6379';
      gitlab_rails['redis_host'] = "redis.gitlab.svc.cluster.local";
      gitlab_rails['redis_port'] = 6379;
{{- if and .Values.gitlab.smtp }} {{if .Values.gitlab.smtp.enable }}
      gitlab_rails['smtp_enable'] = true;
      gitlab_rails['smtp_address'] = {{ .Values.gitlab.smtp.address | quote }};
      gitlab_rails['smtp_port'] = {{ .Values.gitlab.smtp.port | default 645 }};
      gitlab_rails['smtp_user_name'] = {{ .Values.gitlab.smtp.user | quote }};
      gitlab_rails['smtp_password'] = {{ .Values.gitlab.smtp.password | quote }};
      gitlab_rails['smtp_domain'] = {{ .Values.gitlab.smtp.domain | quote }};
      gitlab_rails['smtp_authentication'] = {{ .Values.gitlab.smtp.smtp_authentication | default "login" | quote }};
      gitlab_rails['smtp_enable_starttls_auto'] = {{ .Values.gitlab.smtp.smtp_enable_starttls_auto | default true }};
      gitlab_rails['smtp_openssl_verify_mode'] = {{ .Values.gitlab.smtp.smtp_openssl_verify_mode | default "peer" | quote }};
      gitlab_rails['gitlab_email_from'] = {{ .Values.gitlab.smtp.email_from | quote }};
      gitlab_rails['gitlab_email_reply_to'] = {{ .Values.gitlab.smtp.reply_to | quote }};
{{- end }}{{ end }}
