apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apache-nifi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apache-nifi.labels" . | nindent 4 }}
type: Opaque
stringData:
  SINGLE_USER_CREDENTIALS_PASSWORD: {{ default (randAlphaNum 32) .Values.app.singleUserCredentialsPassword | quote }}
  NIFI_SENSITIVE_PROPS_KEY: {{ default (randAlphaNum 32) .Values.app.nifiSensitivePropsKey | quote}}
