apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apache-nifi-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apache-nifi-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  SINGLE_USER_CREDENTIALS_PASSWORD: {{ default (randAlphaNum 32) .Values.app.singleUserCredentialsPassword | quote }}
  NIFI_SENSITIVE_PROPS_KEY: {{ default (randAlphaNum 32) .Values.app.nifiSensitivePropsKey | quote}}
  {{- if .Values.app.nifiRegistryDbPassword }}
  NIFI_REGISTRY_DB_PASS: {{ .Values.app.nifiRegistryDbPassword | quote }}
  {{- end }}
  # OIDC
  # https://github.com/apache/nifi/blob/main/nifi-registry/nifi-registry-core/nifi-registry-docker/dockerhub/sh/update_oidc_properties.sh
  # NIFI_REGISTRY_SECURITY_USER_OIDC_CLIENT_SECRET: 
