kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "nodered.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
---
# TODO: add volumes to PVC.